name = "cf-vless-ws-yutian81" # todo
#name = "cf-worker-connect-test" # todo
#main = "test/worker/cf-cdn-cgi-trace2.js"
#main = "test/worker/worker-connect-test.js"
main = "_worker.js"
compatibility_date = "2024-04-18"

[vars]
# UUID = "d342d11e-d424-4583-b36e-524ab1f0afa4"
# PROXYIP = "proxyip.jp.fxxk.dedyn.io,ipdb.rr.nu,jp.ipdb.rr.nu"
# DNS_RESOLVER_URL = "https://cloudflare-dns.com/dns-query"
# NODE_ID = "1"
# API_TOKEN = "example_dev_token"
# API_HOST = "api.v2board.com"
# UUID = "1b6c1745-992e-4aac-8685-266c090e50ea,89b64978-6244-4bf3-bf64-67ade4ce5c8f,d342d11e-d424-4583-b36e-524ab1f0afa4"
